-- MySQL Script generated by MySQL Workbench
-- Wed Jun  2 09:20:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parqueadero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parqueadero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parqueadero` ;
USE `parqueadero` ;

-- -----------------------------------------------------
-- Table `parqueadero`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` BIGINT UNSIGNED NOT NULL,
  `direccion` CHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cedula` INT(11) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `telefono` INT(11) NULL,
  `rol` ENUM('cilente', 'empleado') NOT NULL,
  `estado` ENUM('activo', 'inactivo') NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_usuario_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `parqueadero`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`servicio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tarifa_por_hora` SET('No Aplica', '$3.000') NULL,
  `tarifa_mesual` SET('No Aplica', '$40.000') NOT NULL,
  `concepto_autolavado` SET('No Aplica', 'Lavado Interno', 'Tapizado', 'Encerado', 'Pulido') NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicio_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_servicio_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `parqueadero`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`automovil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`automovil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `placa` CHAR(6) NOT NULL,
  `marca` CHAR(20) NOT NULL,
  `color` CHAR(10) NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `tipo` SET('carro', 'buseta', 'moto', 'bicicleta') NOT NULL,
  `estado` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `servicio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_automovil_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_automovil_servicio1_idx` (`servicio_id` ASC),
  CONSTRAINT `fk_automovil_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `parqueadero`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_automovil_servicio1`
    FOREIGN KEY (`servicio_id`)
    REFERENCES `parqueadero`.`servicio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `iva` DECIMAL(3) NOT NULL,
  `precio_total` DECIMAL(10) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `parqueadero`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`deatalleHorarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`deatalleHorarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_de_ingreso` DATETIME(1) NOT NULL,
  `hora_de_salida` DATETIME(1) NOT NULL,
  `factura_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_deatalleHorarios_factura1_idx` (`factura_id` ASC),
  CONSTRAINT `fk_deatalleHorarios_factura1`
    FOREIGN KEY (`factura_id`)
    REFERENCES `parqueadero`.`factura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`municipios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(90) NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_municipios_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `parqueadero`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`insumos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cantidad` VARCHAR(45) NOT NULL,
  `presentasion` VARCHAR(45) NOT NULL,
  `valor` VARCHAR(45) NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_insumos_empresa_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_insumos_empresa`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `parqueadero`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `parqueadero`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parqueadero`.`proveedores` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `empresa_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proveedores_empresa1_idx` (`empresa_id` ASC),
  CONSTRAINT `fk_proveedores_empresa1`
    FOREIGN KEY (`empresa_id`)
    REFERENCES `parqueadero`.`empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
